---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-text-mining/resources/d9pwm) course resource._

---

# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).
* Watch out for potential typos as this is a raw, real-life derived dataset.

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [2]:
import pandas as pd

doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

#df = pd.Series(doc)
#df.head(10)

In [26]:
import re

def date_sorter():
    
    # create dataframe with full text in first column
    df = pd.DataFrame(doc, columns=['text'])
    
    # define formats in which dates will appear
    # try each format, edit and add more as needed until all dates are matched
    
    months = 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec'
    months_dict = {'Jan':'01','Feb':'02','Mar':'03','Apr':'04','May':'05','Jun':'06',
                   'Jul':'07','Aug':'08','Sep':'09','Oct':'10','Nov':'11','Dec':'12'}
        
    # mm/dd/yyyy
    fm1 = '(?P<month>\d{1,2})[/-](?P<day>\d{1,2})[/-](?P<year>\d{2,4})'
    
    # Month dd, yyy
    fm2 = '(?P<month>(?:'+months+')[a-z]*)[ ,.-]+(?P<day>\d{2,4})[ ,.-]+(?P<year>\d{2,4})'
        
    # dd Month yyy
    fm3 = '(?P<day>\d{1,2})[ ,.-](?P<month>(?:'+months+')[a-z]*)[ ,.-](?P<year>\d{2,4})'
        
    # Month yyyy
    fm4 = '\D?(?P<day>[ ]*)(?P<month>(?:'+months+')[a-z]*),?[ ](?P<year>\d{4})'
    
    # mm/yyyy
    fm5 = '\D?(?P<day>)(?P<month>\d{1,2})[/-](?P<year>\d{4})'
    
    # yyyy
    fm6 = '\D?(?P<day>)(?P<month>)(?P<year>[12]\d{3})'
    
    formats = [fm1, fm2, fm3, fm4, fm5, fm6]
    
    # create seperate Series objects for year month and day groups found in text
    years = pd.Series(name='year',index=df.index)
    months = pd.Series(name='month',index=df.index)
    days = pd.Series(name='day',index=df.index)
    
    
    # loop through each text entry
    for i,entry in enumerate(df['text']):
        
        # find format that matches the date in text entry
        for f in formats:
            result = re.search(f,entry)
            
            # found first match, put string groups into respective series and stop search
            if result is not None:
                
                # format and add year
                years.iloc[i] = result.group('year')
                if len(result.group('year')) == 2:
                    years.iloc[i] = '19'+result.group('year')
                
                # format and add month
                months.iloc[i] = result.group('month')
                if result.group('month') == '':
                    months.iloc[i] = '01'
                elif f in [fm2,fm3,fm4]:
                    months.iloc[i] = months_dict[result.group('month').strip()[:3]]
                elif len(result.group('month')) == 1:
                    months.iloc[i] = '0'+result.group('month')
                
                # format and add day
                days.iloc[i] = result.group('day')
                if len(result.group('day').strip()) == 0:
                    days.iloc[i] = '01'
                elif len(result.group('day')) == 1:
                    days.iloc[i] = '0'+result.group('day')
                break
    
        
    # combine date info into yyyymmdd format and add to original text df so it can be sorted chronologically
    df['date'] = years.astype(str)+months.astype(str)+days.astype(str)

    
    
    return pd.Series(df.sort_values(ascending=True,by='date').index)
date_sorter()

0        9
1       84
2        2
3       53
4       28
5      474
6      153
7       13
8      129
9       98
10     111
11     225
12      31
13     171
14     191
15     486
16     335
17     415
18      36
19     405
20     323
21     422
22     375
23     380
24     345
25      57
26     481
27     436
28     104
29     299
      ...
470    220
471    208
472    243
473    139
474    320
475    383
476    244
477    286
478    480
479    431
480    279
481    198
482    381
483    463
484    366
485    439
486    255
487    401
488    475
489    257
490    152
491    235
492    464
493    253
494    427
495    231
496    141
497    186
498    161
499    413
Length: 500, dtype: int64